=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::AddressesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddressesApi' do
  before do
    # run before each test
    @api_instance = Zippendo::AddressesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressesApi' do
    it 'should create an instance of AddressesApi' do
      expect(@api_instance).to be_instance_of(Zippendo::AddressesApi)
    end
  end

  # unit tests for create_address
  # Create address
  # Creates a new sender, pickup or return address for the organization.
  # @param org_id Organization ID
  # @param create_address_request 
  # @param [Hash] opts the optional parameters
  # @return [ListAddresses200ResponseDataInner]
  describe 'create_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_address
  # Delete address
  # Deletes an address belonging to the organization.
  # @param org_id Organization ID
  # @param address_id Address ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'delete_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_address
  # Get address
  # Returns a single address belonging to the organization, identified by its ID.
  # @param org_id Organization ID
  # @param address_id Address ID
  # @param [Hash] opts the optional parameters
  # @return [ListAddresses200ResponseDataInner]
  describe 'get_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_addresses
  # List addresses
  # Returns a paginated list of addresses for the organization, optionally filtered by type.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (1-based)
  # @option opts [Integer] :limit Items per page (max 100)
  # @option opts [String] :type Filter by address type (sender, pickup, return)
  # @return [ListAddresses200Response]
  describe 'list_addresses test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_address
  # Update address
  # Updates an existing address belonging to the organization.
  # @param org_id Organization ID
  # @param address_id Address ID
  # @param update_address_request 
  # @param [Hash] opts the optional parameters
  # @return [ListAddresses200ResponseDataInner]
  describe 'update_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
