=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::BillingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @api_instance = Zippendo::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@api_instance).to be_instance_of(Zippendo::BillingApi)
    end
  end

  # unit tests for get_billing_usage
  # Get usage
  # Get detailed usage statistics for the current billing period.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @return [GetBillingUsage200Response]
  describe 'get_billing_usage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
