=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::CarriersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CarriersApi' do
  before do
    # run before each test
    @api_instance = Zippendo::CarriersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CarriersApi' do
    it 'should create an instance of CarriersApi' do
      expect(@api_instance).to be_instance_of(Zippendo::CarriersApi)
    end
  end

  # unit tests for connect_carrier
  # Connect carrier
  # Connects a new carrier to the organization with its configuration.
  # @param org_id Organization ID
  # @param connect_carrier_request 
  # @param [Hash] opts the optional parameters
  # @return [ListCarriers200ResponseDataInner]
  describe 'connect_carrier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disconnect_carrier
  # Disconnect carrier
  # Disconnects a carrier from the organization.
  # @param org_id Organization ID
  # @param carrier_id Carrier ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'disconnect_carrier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_carrier
  # Get carrier
  # Returns a single connected carrier.
  # @param org_id Organization ID
  # @param carrier_id Carrier ID
  # @param [Hash] opts the optional parameters
  # @return [ListCarriers200ResponseDataInner]
  describe 'get_carrier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_carrier_product_service_points
  # List product service points
  # Returns pickup service points near a location for a specific carrier product.
  # @param org_id Organization ID
  # @param carrier_id Carrier ID
  # @param product_id Carrier product ID
  # @param list_carrier_product_service_points_request 
  # @param [Hash] opts the optional parameters
  # @return [Array<ListCarrierProductServicePoints200ResponseInner>]
  describe 'list_carrier_product_service_points test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_carrier_products
  # List carrier products
  # Returns the shipping products available for a connected carrier.
  # @param org_id Organization ID
  # @param carrier_id Carrier ID
  # @param [Hash] opts the optional parameters
  # @return [Array<ListCarrierProducts200ResponseInner>]
  describe 'list_carrier_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_carriers
  # List carriers
  # Returns a paginated list of carriers connected to the organization.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (1-based)
  # @option opts [Integer] :limit Items per page (max 100)
  # @return [ListCarriers200Response]
  describe 'list_carriers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_carrier
  # Update carrier
  # Updates a connected carrier&#39;s configuration or name.
  # @param org_id Organization ID
  # @param carrier_id Carrier ID
  # @param update_carrier_request 
  # @param [Hash] opts the optional parameters
  # @return [ListCarriers200ResponseDataInner]
  describe 'update_carrier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
