=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::OrgsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrgsApi' do
  before do
    # run before each test
    @api_instance = Zippendo::OrgsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrgsApi' do
    it 'should create an instance of OrgsApi' do
      expect(@api_instance).to be_instance_of(Zippendo::OrgsApi)
    end
  end

  # unit tests for delete_org_logo
  # Delete org logo
  # Removes the org logo. Requires the customBranding entitlement.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @return [GetOrgBranding200Response]
  describe 'delete_org_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_org
  # Get org
  # Returns a specific organization by ID, including its member count.
  # @param id Resource ID
  # @param [Hash] opts the optional parameters
  # @return [GetOrg200Response]
  describe 'get_org test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_org_branding
  # Get org branding
  # Returns the org&#39;s brand colors and an authenticated URL to download the logo.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @return [GetOrgBranding200Response]
  describe 'get_org_branding test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_org_logo
  # Download org logo
  # Returns the org logo image bytes with the stored content type.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_org_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_org
  # Update org
  # Updates an existing organization&#39;s profile, billing, and customs settings.
  # @param id Resource ID
  # @param update_org_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateOrg200Response]
  describe 'update_org test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_org_branding
  # Update org branding
  # Sets the org brand colors. Requires the customBranding entitlement.
  # @param org_id Organization ID
  # @param update_org_branding_request 
  # @param [Hash] opts the optional parameters
  # @return [GetOrgBranding200Response]
  describe 'update_org_branding test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_org_logo
  # Upload org logo
  # Uploads the org logo as multipart/form-data. Accepts PNG, JPG, or WEBP up to 5MB and 4096×4096px; the image is re-encoded and stored. Requires the customBranding entitlement.
  # @param org_id Organization ID
  # @param file Image file (PNG, JPG, or WEBP)
  # @param [Hash] opts the optional parameters
  # @return [GetOrgBranding200Response]
  describe 'upload_org_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
