=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::QuotesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'QuotesApi' do
  before do
    # run before each test
    @api_instance = Zippendo::QuotesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QuotesApi' do
    it 'should create an instance of QuotesApi' do
      expect(@api_instance).to be_instance_of(Zippendo::QuotesApi)
    end
  end

  # unit tests for create_shipping_quote
  # Calculate shipping rates
  # Calculates shipping rates from configured shipping rules based on cart items and destination.
  # @param org_id Organization ID
  # @param create_shipping_quote_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateShippingQuote200Response]
  describe 'create_shipping_quote test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
