=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zippendo::RulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RulesApi' do
  before do
    # run before each test
    @api_instance = Zippendo::RulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RulesApi' do
    it 'should create an instance of RulesApi' do
      expect(@api_instance).to be_instance_of(Zippendo::RulesApi)
    end
  end

  # unit tests for create_shipping_rule
  # Create shipping rule
  # Creates a new shipping rule with conditions and carrier product for the organization.
  # @param org_id Organization ID
  # @param create_shipping_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateShippingRule201Response]
  describe 'create_shipping_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_shipping_rule
  # Delete shipping rule
  # Deletes a shipping rule belonging to the organization.
  # @param org_id Organization ID
  # @param rule_id Shipping Rule ID
  # @param [Hash] opts the optional parameters
  # @return [DeleteShippingRule200Response]
  describe 'delete_shipping_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_shipping_rule
  # Get shipping rule
  # Returns a single shipping rule with its carrier, address and printer relations.
  # @param org_id Organization ID
  # @param rule_id Shipping Rule ID
  # @param [Hash] opts the optional parameters
  # @return [ListShippingRules200ResponseDataInner]
  describe 'get_shipping_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_shipping_rules
  # List shipping rules
  # Returns a paginated list of shipping rules for the organization with their relations.
  # @param org_id Organization ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (1-based)
  # @option opts [Integer] :limit Items per page (max 100)
  # @return [ListShippingRules200Response]
  describe 'list_shipping_rules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_shipping_rule
  # Update shipping rule
  # Updates an existing shipping rule for the organization.
  # @param org_id Organization ID
  # @param rule_id Shipping Rule ID
  # @param update_shipping_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateShippingRule201Response]
  describe 'update_shipping_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
