=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zippendo::CreateShipment201ResponseParcelsInnerDimensions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zippendo::CreateShipment201ResponseParcelsInnerDimensions do
  #let(:instance) { Zippendo::CreateShipment201ResponseParcelsInnerDimensions.new }

  describe 'test an instance of CreateShipment201ResponseParcelsInnerDimensions' do
    it 'should create an instance of CreateShipment201ResponseParcelsInnerDimensions' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zippendo::CreateShipment201ResponseParcelsInnerDimensions)
    end
  end

  describe 'test attribute "length"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "width"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "height"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
