=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zippendo::ListOrders200ResponseDataInnerOrderChannel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zippendo::ListOrders200ResponseDataInnerOrderChannel do
  #let(:instance) { Zippendo::ListOrders200ResponseDataInnerOrderChannel.new }

  describe 'test an instance of ListOrders200ResponseDataInnerOrderChannel' do
    it 'should create an instance of ListOrders200ResponseDataInnerOrderChannel' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zippendo::ListOrders200ResponseDataInnerOrderChannel)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["shopify", "woocommerce", "manual"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
