=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zippendo::SplitShipmentParcelRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zippendo::SplitShipmentParcelRequest do
  #let(:instance) { Zippendo::SplitShipmentParcelRequest.new }

  describe 'test an instance of SplitShipmentParcelRequest' do
    it 'should create an instance of SplitShipmentParcelRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zippendo::SplitShipmentParcelRequest)
    end
  end

  describe 'test attribute "parcels"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
