=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zippendo::UpdateCarrierRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zippendo::UpdateCarrierRequest do
  #let(:instance) { Zippendo::UpdateCarrierRequest.new }

  describe 'test an instance of UpdateCarrierRequest' do
    it 'should create an instance of UpdateCarrierRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zippendo::UpdateCarrierRequest)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "carrier_slug"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "config"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
