=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class CreateShipment201Response < ApiModelBase
    # Unique shipment identifier.
    attr_accessor :id

    # Customer-facing shipment reference.
    attr_accessor :reference

    # Sender address identifier.
    attr_accessor :address_id

    # Selected carrier service point identifier.
    attr_accessor :service_point_id

    # Parties involved in the shipment (sender, receiver, etc.).
    attr_accessor :parties

    # Direction of the shipment relative to the organization.
    attr_accessor :type

    attr_accessor :carrier_settings

    # Parcels included in the shipment.
    attr_accessor :parcels

    attr_accessor :pickup_details

    # Incoterm governing the shipment.
    attr_accessor :term_of_trade

    # Documents generated for the shipment (labels, invoices).
    attr_accessor :documents

    # Carrier errors recorded for the shipment.
    attr_accessor :errors

    attr_accessor :tracking

    # Lifecycle status of the shipment.
    attr_accessor :status

    # Owning organization identifier.
    attr_accessor :org_id

    # Associated order identifier.
    attr_accessor :order_id

    # Applied shipping rule identifier.
    attr_accessor :shipping_rule_id

    attr_accessor :shipping_rule

    # Printer assigned for labels on this shipment.
    attr_accessor :label_printer_id

    # Printer assigned for documents on this shipment.
    attr_accessor :document_printer_id

    # Request/response logs captured during carrier interactions.
    attr_accessor :logs

    # Chronological activity history of the shipment.
    attr_accessor :activities

    # Timestamp when the shipment was created.
    attr_accessor :created_at

    # Timestamp when the shipment was last updated.
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'reference' => :'reference',
        :'address_id' => :'addressId',
        :'service_point_id' => :'servicePointId',
        :'parties' => :'parties',
        :'type' => :'type',
        :'carrier_settings' => :'carrierSettings',
        :'parcels' => :'parcels',
        :'pickup_details' => :'pickupDetails',
        :'term_of_trade' => :'termOfTrade',
        :'documents' => :'documents',
        :'errors' => :'errors',
        :'tracking' => :'tracking',
        :'status' => :'status',
        :'org_id' => :'orgId',
        :'order_id' => :'orderId',
        :'shipping_rule_id' => :'shippingRuleId',
        :'shipping_rule' => :'shippingRule',
        :'label_printer_id' => :'labelPrinterId',
        :'document_printer_id' => :'documentPrinterId',
        :'logs' => :'logs',
        :'activities' => :'activities',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'reference' => :'String',
        :'address_id' => :'String',
        :'service_point_id' => :'String',
        :'parties' => :'Array<CreateShipment201ResponsePartiesInner>',
        :'type' => :'String',
        :'carrier_settings' => :'ListShipments200ResponseDataInnerCarrierSettings',
        :'parcels' => :'Array<CreateShipment201ResponseParcelsInner>',
        :'pickup_details' => :'CreateShipment201ResponsePickupDetails',
        :'term_of_trade' => :'String',
        :'documents' => :'Array<CreateShipment201ResponseDocumentsInner>',
        :'errors' => :'Array<CreateShipment201ResponseErrorsInner>',
        :'tracking' => :'CreateShipment201ResponseTracking',
        :'status' => :'String',
        :'org_id' => :'String',
        :'order_id' => :'String',
        :'shipping_rule_id' => :'String',
        :'shipping_rule' => :'CreateShipment201ResponseShippingRule',
        :'label_printer_id' => :'String',
        :'document_printer_id' => :'String',
        :'logs' => :'Array<CreateShipment201ResponseLogsInner>',
        :'activities' => :'Array<CreateShipment201ResponseActivitiesInner>',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'address_id',
        :'service_point_id',
        :'pickup_details',
        :'tracking',
        :'order_id',
        :'shipping_rule_id',
        :'shipping_rule',
        :'label_printer_id',
        :'document_printer_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::CreateShipment201Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::CreateShipment201Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      else
        self.reference = nil
      end

      if attributes.key?(:'address_id')
        self.address_id = attributes[:'address_id']
      end

      if attributes.key?(:'service_point_id')
        self.service_point_id = attributes[:'service_point_id']
      end

      if attributes.key?(:'parties')
        if (value = attributes[:'parties']).is_a?(Array)
          self.parties = value
        end
      else
        self.parties = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'carrier_settings')
        self.carrier_settings = attributes[:'carrier_settings']
      else
        self.carrier_settings = nil
      end

      if attributes.key?(:'parcels')
        if (value = attributes[:'parcels']).is_a?(Array)
          self.parcels = value
        end
      else
        self.parcels = nil
      end

      if attributes.key?(:'pickup_details')
        self.pickup_details = attributes[:'pickup_details']
      end

      if attributes.key?(:'term_of_trade')
        self.term_of_trade = attributes[:'term_of_trade']
      else
        self.term_of_trade = 'DAP'
      end

      if attributes.key?(:'documents')
        if (value = attributes[:'documents']).is_a?(Array)
          self.documents = value
        end
      end

      if attributes.key?(:'errors')
        if (value = attributes[:'errors']).is_a?(Array)
          self.errors = value
        end
      else
        self.errors = nil
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'shipping_rule_id')
        self.shipping_rule_id = attributes[:'shipping_rule_id']
      end

      if attributes.key?(:'shipping_rule')
        self.shipping_rule = attributes[:'shipping_rule']
      end

      if attributes.key?(:'label_printer_id')
        self.label_printer_id = attributes[:'label_printer_id']
      end

      if attributes.key?(:'document_printer_id')
        self.document_printer_id = attributes[:'document_printer_id']
      end

      if attributes.key?(:'logs')
        if (value = attributes[:'logs']).is_a?(Array)
          self.logs = value
        end
      else
        self.logs = nil
      end

      if attributes.key?(:'activities')
        if (value = attributes[:'activities']).is_a?(Array)
          self.activities = value
        end
      else
        self.activities = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @reference.nil?
        invalid_properties.push('invalid value for "reference", reference cannot be nil.')
      end

      if @parties.nil?
        invalid_properties.push('invalid value for "parties", parties cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @carrier_settings.nil?
        invalid_properties.push('invalid value for "carrier_settings", carrier_settings cannot be nil.')
      end

      if @parcels.nil?
        invalid_properties.push('invalid value for "parcels", parcels cannot be nil.')
      end

      if @term_of_trade.nil?
        invalid_properties.push('invalid value for "term_of_trade", term_of_trade cannot be nil.')
      end

      if @errors.nil?
        invalid_properties.push('invalid value for "errors", errors cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @logs.nil?
        invalid_properties.push('invalid value for "logs", logs cannot be nil.')
      end

      if @activities.nil?
        invalid_properties.push('invalid value for "activities", activities cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @reference.nil?
      return false if @parties.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      return false unless type_validator.valid?(@type)
      return false if @carrier_settings.nil?
      return false if @parcels.nil?
      return false if @term_of_trade.nil?
      return false if @errors.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["draft", "pending", "processing", "dispatched", "partly_dispatched", "error", "cancelled", "on_hold"])
      return false unless status_validator.valid?(@status)
      return false if @org_id.nil?
      return false if @logs.nil?
      return false if @activities.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] reference Value to be assigned
    def reference=(reference)
      if reference.nil?
        fail ArgumentError, 'reference cannot be nil'
      end

      @reference = reference
    end

    # Custom attribute writer method with validation
    # @param [Object] parties Value to be assigned
    def parties=(parties)
      if parties.nil?
        fail ArgumentError, 'parties cannot be nil'
      end

      @parties = parties
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_settings Value to be assigned
    def carrier_settings=(carrier_settings)
      if carrier_settings.nil?
        fail ArgumentError, 'carrier_settings cannot be nil'
      end

      @carrier_settings = carrier_settings
    end

    # Custom attribute writer method with validation
    # @param [Object] parcels Value to be assigned
    def parcels=(parcels)
      if parcels.nil?
        fail ArgumentError, 'parcels cannot be nil'
      end

      @parcels = parcels
    end

    # Custom attribute writer method with validation
    # @param [Object] term_of_trade Value to be assigned
    def term_of_trade=(term_of_trade)
      if term_of_trade.nil?
        fail ArgumentError, 'term_of_trade cannot be nil'
      end

      @term_of_trade = term_of_trade
    end

    # Custom attribute writer method with validation
    # @param [Object] errors Value to be assigned
    def errors=(errors)
      if errors.nil?
        fail ArgumentError, 'errors cannot be nil'
      end

      @errors = errors
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["draft", "pending", "processing", "dispatched", "partly_dispatched", "error", "cancelled", "on_hold"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] logs Value to be assigned
    def logs=(logs)
      if logs.nil?
        fail ArgumentError, 'logs cannot be nil'
      end

      @logs = logs
    end

    # Custom attribute writer method with validation
    # @param [Object] activities Value to be assigned
    def activities=(activities)
      if activities.nil?
        fail ArgumentError, 'activities cannot be nil'
      end

      @activities = activities
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          reference == o.reference &&
          address_id == o.address_id &&
          service_point_id == o.service_point_id &&
          parties == o.parties &&
          type == o.type &&
          carrier_settings == o.carrier_settings &&
          parcels == o.parcels &&
          pickup_details == o.pickup_details &&
          term_of_trade == o.term_of_trade &&
          documents == o.documents &&
          errors == o.errors &&
          tracking == o.tracking &&
          status == o.status &&
          org_id == o.org_id &&
          order_id == o.order_id &&
          shipping_rule_id == o.shipping_rule_id &&
          shipping_rule == o.shipping_rule &&
          label_printer_id == o.label_printer_id &&
          document_printer_id == o.document_printer_id &&
          logs == o.logs &&
          activities == o.activities &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, reference, address_id, service_point_id, parties, type, carrier_settings, parcels, pickup_details, term_of_trade, documents, errors, tracking, status, org_id, order_id, shipping_rule_id, shipping_rule, label_printer_id, document_printer_id, logs, activities, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
