=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class CreateOrder201Response < ApiModelBase
    # Unique order ID.
    attr_accessor :id

    # Human-readable order number.
    attr_accessor :order_number

    # Identifier of the order in the source platform.
    attr_accessor :external_id

    # Customer full name.
    attr_accessor :customer_name

    # Customer email address.
    attr_accessor :customer_email

    attr_accessor :shipping_address

    # Line items in the order.
    attr_accessor :order_lines

    # Order subtotal before shipping and tax.
    attr_accessor :subtotal_amount

    # Order grand total.
    attr_accessor :total_amount

    # ISO 4217 currency code.
    attr_accessor :currency

    # Order fulfilment status derived from its shipments.
    attr_accessor :status

    # ID of the applied shipping rule.
    attr_accessor :shipping_rule_id

    # Free-form internal notes.
    attr_accessor :notes

    # Raw platform-specific payload for reference.
    attr_accessor :external_data

    # ID of the order channel this order belongs to.
    attr_accessor :order_channel_id

    # Owning organization ID.
    attr_accessor :org_id

    # Creation timestamp (ISO 8601).
    attr_accessor :created_at

    # Last update timestamp (ISO 8601).
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'order_number' => :'orderNumber',
        :'external_id' => :'externalId',
        :'customer_name' => :'customerName',
        :'customer_email' => :'customerEmail',
        :'shipping_address' => :'shippingAddress',
        :'order_lines' => :'orderLines',
        :'subtotal_amount' => :'subtotalAmount',
        :'total_amount' => :'totalAmount',
        :'currency' => :'currency',
        :'status' => :'status',
        :'shipping_rule_id' => :'shippingRuleId',
        :'notes' => :'notes',
        :'external_data' => :'externalData',
        :'order_channel_id' => :'orderChannelId',
        :'org_id' => :'orgId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'order_number' => :'String',
        :'external_id' => :'String',
        :'customer_name' => :'String',
        :'customer_email' => :'String',
        :'shipping_address' => :'CreateOrder201ResponseShippingAddress',
        :'order_lines' => :'Array<CreateOrder201ResponseOrderLinesInner>',
        :'subtotal_amount' => :'Float',
        :'total_amount' => :'Float',
        :'currency' => :'String',
        :'status' => :'String',
        :'shipping_rule_id' => :'String',
        :'notes' => :'String',
        :'external_data' => :'Hash<String, Object>',
        :'order_channel_id' => :'String',
        :'org_id' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'external_id',
        :'customer_name',
        :'customer_email',
        :'shipping_address',
        :'subtotal_amount',
        :'total_amount',
        :'currency',
        :'shipping_rule_id',
        :'notes',
        :'external_data',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::CreateOrder201Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::CreateOrder201Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'order_number')
        self.order_number = attributes[:'order_number']
      else
        self.order_number = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'shipping_address')
        self.shipping_address = attributes[:'shipping_address']
      end

      if attributes.key?(:'order_lines')
        if (value = attributes[:'order_lines']).is_a?(Array)
          self.order_lines = value
        end
      else
        self.order_lines = nil
      end

      if attributes.key?(:'subtotal_amount')
        self.subtotal_amount = attributes[:'subtotal_amount']
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'shipping_rule_id')
        self.shipping_rule_id = attributes[:'shipping_rule_id']
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'external_data')
        if (value = attributes[:'external_data']).is_a?(Hash)
          self.external_data = value
        end
      end

      if attributes.key?(:'order_channel_id')
        self.order_channel_id = attributes[:'order_channel_id']
      else
        self.order_channel_id = nil
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @order_number.nil?
        invalid_properties.push('invalid value for "order_number", order_number cannot be nil.')
      end

      if @order_lines.nil?
        invalid_properties.push('invalid value for "order_lines", order_lines cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @order_channel_id.nil?
        invalid_properties.push('invalid value for "order_channel_id", order_channel_id cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @order_number.nil?
      return false if @order_lines.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["pending", "processing", "partially_fulfilled", "fulfilled", "error", "cancelled"])
      return false unless status_validator.valid?(@status)
      return false if @order_channel_id.nil?
      return false if @org_id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] order_number Value to be assigned
    def order_number=(order_number)
      if order_number.nil?
        fail ArgumentError, 'order_number cannot be nil'
      end

      @order_number = order_number
    end

    # Custom attribute writer method with validation
    # @param [Object] order_lines Value to be assigned
    def order_lines=(order_lines)
      if order_lines.nil?
        fail ArgumentError, 'order_lines cannot be nil'
      end

      @order_lines = order_lines
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["pending", "processing", "partially_fulfilled", "fulfilled", "error", "cancelled"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] order_channel_id Value to be assigned
    def order_channel_id=(order_channel_id)
      if order_channel_id.nil?
        fail ArgumentError, 'order_channel_id cannot be nil'
      end

      @order_channel_id = order_channel_id
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          order_number == o.order_number &&
          external_id == o.external_id &&
          customer_name == o.customer_name &&
          customer_email == o.customer_email &&
          shipping_address == o.shipping_address &&
          order_lines == o.order_lines &&
          subtotal_amount == o.subtotal_amount &&
          total_amount == o.total_amount &&
          currency == o.currency &&
          status == o.status &&
          shipping_rule_id == o.shipping_rule_id &&
          notes == o.notes &&
          external_data == o.external_data &&
          order_channel_id == o.order_channel_id &&
          org_id == o.org_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, order_number, external_id, customer_name, customer_email, shipping_address, order_lines, subtotal_amount, total_amount, currency, status, shipping_rule_id, notes, external_data, order_channel_id, org_id, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
