=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class CreateShipmentRequestParcelsInner < ApiModelBase
    # Unique parcel identifier.
    attr_accessor :id

    # Parcel weight in the given weight unit.
    attr_accessor :weight

    # Unit of measurement for parcel weight.
    attr_accessor :weight_unit

    attr_accessor :dimensions

    # Order lines contained in this parcel.
    attr_accessor :order_lines

    # Carrier tracking number for this parcel.
    attr_accessor :tracking_number

    # Public carrier tracking URL for this parcel.
    attr_accessor :tracking_url

    # Label-free drop-off code for the parcel.
    attr_accessor :label_free_code

    # DEPRECATED — use `qrCodeDataUri` (embeddable data URI) or `qrCodeUrl` (hosted link). Catch-all that carries whichever applies, kept populated for backwards compatibility during the migration and until it is disabled.
    attr_accessor :qr_code_link

    # Embeddable `data:` URI of the QR code image for label-free drop-off — base64 image bytes you can drop straight into an <img>/email. Null when the carrier returns a hosted link instead (see `qrCodeUrl`).
    attr_accessor :qr_code_data_uri

    # Carrier-hosted URL of the QR code image for label-free drop-off, returned by carriers (e.g. Bring) that link to the image rather than embedding it. Null when the carrier returns embeddable bytes (see `qrCodeDataUri`).
    attr_accessor :qr_code_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'weight' => :'weight',
        :'weight_unit' => :'weightUnit',
        :'dimensions' => :'dimensions',
        :'order_lines' => :'orderLines',
        :'tracking_number' => :'trackingNumber',
        :'tracking_url' => :'trackingUrl',
        :'label_free_code' => :'labelFreeCode',
        :'qr_code_link' => :'qrCodeLink',
        :'qr_code_data_uri' => :'qrCodeDataUri',
        :'qr_code_url' => :'qrCodeUrl'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'weight' => :'Float',
        :'weight_unit' => :'String',
        :'dimensions' => :'CreateShipmentRequestParcelsInnerDimensions',
        :'order_lines' => :'Array<CreateShipmentRequestParcelsInnerOrderLinesInner>',
        :'tracking_number' => :'String',
        :'tracking_url' => :'String',
        :'label_free_code' => :'String',
        :'qr_code_link' => :'String',
        :'qr_code_data_uri' => :'String',
        :'qr_code_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tracking_number',
        :'tracking_url',
        :'label_free_code',
        :'qr_code_link',
        :'qr_code_data_uri',
        :'qr_code_url'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::CreateShipmentRequestParcelsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::CreateShipmentRequestParcelsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      else
        self.weight = nil
      end

      if attributes.key?(:'weight_unit')
        self.weight_unit = attributes[:'weight_unit']
      else
        self.weight_unit = nil
      end

      if attributes.key?(:'dimensions')
        self.dimensions = attributes[:'dimensions']
      else
        self.dimensions = nil
      end

      if attributes.key?(:'order_lines')
        if (value = attributes[:'order_lines']).is_a?(Array)
          self.order_lines = value
        end
      else
        self.order_lines = nil
      end

      if attributes.key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      end

      if attributes.key?(:'tracking_url')
        self.tracking_url = attributes[:'tracking_url']
      end

      if attributes.key?(:'label_free_code')
        self.label_free_code = attributes[:'label_free_code']
      end

      if attributes.key?(:'qr_code_link')
        self.qr_code_link = attributes[:'qr_code_link']
      end

      if attributes.key?(:'qr_code_data_uri')
        self.qr_code_data_uri = attributes[:'qr_code_data_uri']
      end

      if attributes.key?(:'qr_code_url')
        self.qr_code_url = attributes[:'qr_code_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @weight.nil?
        invalid_properties.push('invalid value for "weight", weight cannot be nil.')
      end

      if @weight < 0
        invalid_properties.push('invalid value for "weight", must be greater than or equal to 0.')
      end

      if @weight_unit.nil?
        invalid_properties.push('invalid value for "weight_unit", weight_unit cannot be nil.')
      end

      if @dimensions.nil?
        invalid_properties.push('invalid value for "dimensions", dimensions cannot be nil.')
      end

      if @order_lines.nil?
        invalid_properties.push('invalid value for "order_lines", order_lines cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @weight.nil?
      return false if @weight < 0
      return false if @weight_unit.nil?
      weight_unit_validator = EnumAttributeValidator.new('String', ["kg", "g", "lb", "oz"])
      return false unless weight_unit_validator.valid?(@weight_unit)
      return false if @dimensions.nil?
      return false if @order_lines.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] weight Value to be assigned
    def weight=(weight)
      if weight.nil?
        fail ArgumentError, 'weight cannot be nil'
      end

      if weight < 0
        fail ArgumentError, 'invalid value for "weight", must be greater than or equal to 0.'
      end

      @weight = weight
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] weight_unit Object to be assigned
    def weight_unit=(weight_unit)
      validator = EnumAttributeValidator.new('String', ["kg", "g", "lb", "oz"])
      unless validator.valid?(weight_unit)
        fail ArgumentError, "invalid value for \"weight_unit\", must be one of #{validator.allowable_values}."
      end
      @weight_unit = weight_unit
    end

    # Custom attribute writer method with validation
    # @param [Object] dimensions Value to be assigned
    def dimensions=(dimensions)
      if dimensions.nil?
        fail ArgumentError, 'dimensions cannot be nil'
      end

      @dimensions = dimensions
    end

    # Custom attribute writer method with validation
    # @param [Object] order_lines Value to be assigned
    def order_lines=(order_lines)
      if order_lines.nil?
        fail ArgumentError, 'order_lines cannot be nil'
      end

      @order_lines = order_lines
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          weight == o.weight &&
          weight_unit == o.weight_unit &&
          dimensions == o.dimensions &&
          order_lines == o.order_lines &&
          tracking_number == o.tracking_number &&
          tracking_url == o.tracking_url &&
          label_free_code == o.label_free_code &&
          qr_code_link == o.qr_code_link &&
          qr_code_data_uri == o.qr_code_data_uri &&
          qr_code_url == o.qr_code_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, weight, weight_unit, dimensions, order_lines, tracking_number, tracking_url, label_free_code, qr_code_link, qr_code_data_uri, qr_code_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
