=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class CreateShipmentRequest < ApiModelBase
    # Customer-facing shipment reference.
    attr_accessor :reference

    # Sender address identifier.
    attr_accessor :address_id

    # Selected carrier service point identifier.
    attr_accessor :service_point_id

    # Parties involved in the shipment. Optional when orderId is provided.
    attr_accessor :parties

    # Direction of the shipment relative to the organization.
    attr_accessor :type

    attr_accessor :carrier_settings

    # Parcels to include. Optional when orderId is provided.
    attr_accessor :parcels

    attr_accessor :pickup_details

    # Incoterm governing the shipment.
    attr_accessor :term_of_trade

    # Lifecycle status of the shipment.
    attr_accessor :status

    # Order to derive parties and parcels from.
    attr_accessor :order_id

    # Printer to assign for labels.
    attr_accessor :label_printer_id

    # Printer to assign for documents.
    attr_accessor :document_printer_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'reference' => :'reference',
        :'address_id' => :'addressId',
        :'service_point_id' => :'servicePointId',
        :'parties' => :'parties',
        :'type' => :'type',
        :'carrier_settings' => :'carrierSettings',
        :'parcels' => :'parcels',
        :'pickup_details' => :'pickupDetails',
        :'term_of_trade' => :'termOfTrade',
        :'status' => :'status',
        :'order_id' => :'orderId',
        :'label_printer_id' => :'labelPrinterId',
        :'document_printer_id' => :'documentPrinterId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'reference' => :'String',
        :'address_id' => :'String',
        :'service_point_id' => :'String',
        :'parties' => :'Array<CreateShipmentRequestPartiesInner>',
        :'type' => :'String',
        :'carrier_settings' => :'CreateShipmentRequestCarrierSettings',
        :'parcels' => :'Array<CreateShipmentRequestParcelsInner>',
        :'pickup_details' => :'CreateShipmentRequestPickupDetails',
        :'term_of_trade' => :'String',
        :'status' => :'String',
        :'order_id' => :'String',
        :'label_printer_id' => :'String',
        :'document_printer_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'address_id',
        :'service_point_id',
        :'pickup_details',
        :'order_id',
        :'label_printer_id',
        :'document_printer_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::CreateShipmentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::CreateShipmentRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      end

      if attributes.key?(:'address_id')
        self.address_id = attributes[:'address_id']
      end

      if attributes.key?(:'service_point_id')
        self.service_point_id = attributes[:'service_point_id']
      end

      if attributes.key?(:'parties')
        if (value = attributes[:'parties']).is_a?(Array)
          self.parties = value
        end
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'carrier_settings')
        self.carrier_settings = attributes[:'carrier_settings']
      else
        self.carrier_settings = nil
      end

      if attributes.key?(:'parcels')
        if (value = attributes[:'parcels']).is_a?(Array)
          self.parcels = value
        end
      end

      if attributes.key?(:'pickup_details')
        self.pickup_details = attributes[:'pickup_details']
      end

      if attributes.key?(:'term_of_trade')
        self.term_of_trade = attributes[:'term_of_trade']
      else
        self.term_of_trade = 'DAP'
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = 'pending'
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'label_printer_id')
        self.label_printer_id = attributes[:'label_printer_id']
      end

      if attributes.key?(:'document_printer_id')
        self.document_printer_id = attributes[:'document_printer_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@reference.nil? && @reference.to_s.length < 1
        invalid_properties.push('invalid value for "reference", the character length must be greater than or equal to 1.')
      end

      if !@parties.nil? && @parties.length < 1
        invalid_properties.push('invalid value for "parties", number of items must be greater than or equal to 1.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @carrier_settings.nil?
        invalid_properties.push('invalid value for "carrier_settings", carrier_settings cannot be nil.')
      end

      if !@parcels.nil? && @parcels.length < 1
        invalid_properties.push('invalid value for "parcels", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@reference.nil? && @reference.to_s.length < 1
      return false if !@parties.nil? && @parties.length < 1
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      return false unless type_validator.valid?(@type)
      return false if @carrier_settings.nil?
      return false if !@parcels.nil? && @parcels.length < 1
      status_validator = EnumAttributeValidator.new('String', ["draft", "pending", "processing", "dispatched", "partly_dispatched", "error", "cancelled", "on_hold"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] reference Value to be assigned
    def reference=(reference)
      if reference.nil?
        fail ArgumentError, 'reference cannot be nil'
      end

      if reference.to_s.length < 1
        fail ArgumentError, 'invalid value for "reference", the character length must be greater than or equal to 1.'
      end

      @reference = reference
    end

    # Custom attribute writer method with validation
    # @param [Object] parties Value to be assigned
    def parties=(parties)
      if parties.nil?
        fail ArgumentError, 'parties cannot be nil'
      end

      if parties.length < 1
        fail ArgumentError, 'invalid value for "parties", number of items must be greater than or equal to 1.'
      end

      @parties = parties
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_settings Value to be assigned
    def carrier_settings=(carrier_settings)
      if carrier_settings.nil?
        fail ArgumentError, 'carrier_settings cannot be nil'
      end

      @carrier_settings = carrier_settings
    end

    # Custom attribute writer method with validation
    # @param [Object] parcels Value to be assigned
    def parcels=(parcels)
      if parcels.nil?
        fail ArgumentError, 'parcels cannot be nil'
      end

      if parcels.length < 1
        fail ArgumentError, 'invalid value for "parcels", number of items must be greater than or equal to 1.'
      end

      @parcels = parcels
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["draft", "pending", "processing", "dispatched", "partly_dispatched", "error", "cancelled", "on_hold"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          reference == o.reference &&
          address_id == o.address_id &&
          service_point_id == o.service_point_id &&
          parties == o.parties &&
          type == o.type &&
          carrier_settings == o.carrier_settings &&
          parcels == o.parcels &&
          pickup_details == o.pickup_details &&
          term_of_trade == o.term_of_trade &&
          status == o.status &&
          order_id == o.order_id &&
          label_printer_id == o.label_printer_id &&
          document_printer_id == o.document_printer_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [reference, address_id, service_point_id, parties, type, carrier_settings, parcels, pickup_details, term_of_trade, status, order_id, label_printer_id, document_printer_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
