=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class ListShippingRules200ResponseDataInner < ApiModelBase
    # Unique shipping rule identifier
    attr_accessor :id

    # Shipping rule name
    attr_accessor :name

    # Optional description
    attr_accessor :description

    # Whether this rule is for outbound or inbound (return) shipments
    attr_accessor :direction

    # Carrier ID
    attr_accessor :carrier_id

    # Product ID from carrier
    attr_accessor :product_id

    # List of selected services
    attr_accessor :services

    # Carrier-specific extra parameters. DEPRECATED array form `[{ name, val }]` where `name` is the carrier parameter `key` (from the product's `additionalParameters[].key`, e.g. `returnFunctionality`) and `val` is the stringified value. This will change to a `{ key: value }` object in a future version — writes already accept either shape.
    attr_accessor :additional_parameters

    # Sender address ID
    attr_accessor :address_id

    # List of supported country codes
    attr_accessor :receiving_countries

    # Send email notification to recipient
    attr_accessor :email_notification

    # Send SMS notification to recipient
    attr_accessor :phone_notification

    # Minimum required weight in kg. Orders below this are excluded from the rule.
    attr_accessor :min_weight

    # Maximum allowed weight in kg. Orders exceeding this are excluded from the rule.
    attr_accessor :max_weight

    # Minimum required order value in currency units. Orders below this are excluded from the rule.
    attr_accessor :min_order_value

    # Maximum allowed order value in currency units. Orders exceeding this are excluded from the rule.
    attr_accessor :max_order_value

    # Rule conditions (weight/price/quantity)
    attr_accessor :conditions

    # Generate proforma invoice for shipments
    attr_accessor :generate_proforma_invoice

    # Generate commercial invoice for international shipments
    attr_accessor :generate_commercial_invoice

    # Generate packing slip with package and item details
    attr_accessor :generate_packing_list

    # Automatically print labels when shipment is sent
    attr_accessor :auto_print_labels

    # Automatically print documents when shipment is sent
    attr_accessor :auto_print_documents

    # ID of the label printer
    attr_accessor :label_printer_id

    # ID of the document printer
    attr_accessor :document_printer_id

    # ID of the return shipping rule
    attr_accessor :return_shipping_rule_id

    # Automatically create and send a return shipment on dispatch
    attr_accessor :auto_create_return_shipment

    # Owning organization ID
    attr_accessor :org_id

    # Creation timestamp (ISO 8601)
    attr_accessor :created_at

    # Last update timestamp (ISO 8601)
    attr_accessor :updated_at

    attr_accessor :carrier

    attr_accessor :address

    attr_accessor :label_printer

    attr_accessor :document_printer

    attr_accessor :return_shipping_rule

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'description' => :'description',
        :'direction' => :'direction',
        :'carrier_id' => :'carrierId',
        :'product_id' => :'productId',
        :'services' => :'services',
        :'additional_parameters' => :'additionalParameters',
        :'address_id' => :'addressId',
        :'receiving_countries' => :'receivingCountries',
        :'email_notification' => :'emailNotification',
        :'phone_notification' => :'phoneNotification',
        :'min_weight' => :'minWeight',
        :'max_weight' => :'maxWeight',
        :'min_order_value' => :'minOrderValue',
        :'max_order_value' => :'maxOrderValue',
        :'conditions' => :'conditions',
        :'generate_proforma_invoice' => :'generateProformaInvoice',
        :'generate_commercial_invoice' => :'generateCommercialInvoice',
        :'generate_packing_list' => :'generatePackingList',
        :'auto_print_labels' => :'autoPrintLabels',
        :'auto_print_documents' => :'autoPrintDocuments',
        :'label_printer_id' => :'labelPrinterId',
        :'document_printer_id' => :'documentPrinterId',
        :'return_shipping_rule_id' => :'returnShippingRuleId',
        :'auto_create_return_shipment' => :'autoCreateReturnShipment',
        :'org_id' => :'orgId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'carrier' => :'carrier',
        :'address' => :'address',
        :'label_printer' => :'labelPrinter',
        :'document_printer' => :'documentPrinter',
        :'return_shipping_rule' => :'returnShippingRule'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'direction' => :'String',
        :'carrier_id' => :'String',
        :'product_id' => :'String',
        :'services' => :'Array<String>',
        :'additional_parameters' => :'Array<ListShippingRules200ResponseDataInnerAdditionalParametersInner>',
        :'address_id' => :'String',
        :'receiving_countries' => :'Array<String>',
        :'email_notification' => :'Boolean',
        :'phone_notification' => :'Boolean',
        :'min_weight' => :'Float',
        :'max_weight' => :'Float',
        :'min_order_value' => :'Float',
        :'max_order_value' => :'Float',
        :'conditions' => :'Array<ListShippingRules200ResponseDataInnerConditionsInner>',
        :'generate_proforma_invoice' => :'Boolean',
        :'generate_commercial_invoice' => :'Boolean',
        :'generate_packing_list' => :'Boolean',
        :'auto_print_labels' => :'Boolean',
        :'auto_print_documents' => :'Boolean',
        :'label_printer_id' => :'String',
        :'document_printer_id' => :'String',
        :'return_shipping_rule_id' => :'String',
        :'auto_create_return_shipment' => :'Boolean',
        :'org_id' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'carrier' => :'ListShippingRules200ResponseDataInnerCarrier',
        :'address' => :'ListAddresses200ResponseDataInner',
        :'label_printer' => :'ListShippingRules200ResponseDataInnerLabelPrinter',
        :'document_printer' => :'ListShippingRules200ResponseDataInnerLabelPrinter',
        :'return_shipping_rule' => :'ListShippingRules200ResponseDataInnerReturnShippingRule'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'min_weight',
        :'max_weight',
        :'min_order_value',
        :'max_order_value',
        :'label_printer_id',
        :'document_printer_id',
        :'return_shipping_rule_id',
        :'label_printer',
        :'document_printer',
        :'return_shipping_rule'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::ListShippingRules200ResponseDataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::ListShippingRules200ResponseDataInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = 'outbound'
      end

      if attributes.key?(:'carrier_id')
        self.carrier_id = attributes[:'carrier_id']
      else
        self.carrier_id = nil
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'services')
        if (value = attributes[:'services']).is_a?(Array)
          self.services = value
        end
      else
        self.services = nil
      end

      if attributes.key?(:'additional_parameters')
        if (value = attributes[:'additional_parameters']).is_a?(Array)
          self.additional_parameters = value
        end
      else
        self.additional_parameters = nil
      end

      if attributes.key?(:'address_id')
        self.address_id = attributes[:'address_id']
      else
        self.address_id = nil
      end

      if attributes.key?(:'receiving_countries')
        if (value = attributes[:'receiving_countries']).is_a?(Array)
          self.receiving_countries = value
        end
      else
        self.receiving_countries = nil
      end

      if attributes.key?(:'email_notification')
        self.email_notification = attributes[:'email_notification']
      else
        self.email_notification = false
      end

      if attributes.key?(:'phone_notification')
        self.phone_notification = attributes[:'phone_notification']
      else
        self.phone_notification = false
      end

      if attributes.key?(:'min_weight')
        self.min_weight = attributes[:'min_weight']
      else
        self.min_weight = nil
      end

      if attributes.key?(:'max_weight')
        self.max_weight = attributes[:'max_weight']
      else
        self.max_weight = nil
      end

      if attributes.key?(:'min_order_value')
        self.min_order_value = attributes[:'min_order_value']
      else
        self.min_order_value = nil
      end

      if attributes.key?(:'max_order_value')
        self.max_order_value = attributes[:'max_order_value']
      else
        self.max_order_value = nil
      end

      if attributes.key?(:'conditions')
        if (value = attributes[:'conditions']).is_a?(Array)
          self.conditions = value
        end
      else
        self.conditions = nil
      end

      if attributes.key?(:'generate_proforma_invoice')
        self.generate_proforma_invoice = attributes[:'generate_proforma_invoice']
      else
        self.generate_proforma_invoice = false
      end

      if attributes.key?(:'generate_commercial_invoice')
        self.generate_commercial_invoice = attributes[:'generate_commercial_invoice']
      else
        self.generate_commercial_invoice = false
      end

      if attributes.key?(:'generate_packing_list')
        self.generate_packing_list = attributes[:'generate_packing_list']
      else
        self.generate_packing_list = false
      end

      if attributes.key?(:'auto_print_labels')
        self.auto_print_labels = attributes[:'auto_print_labels']
      else
        self.auto_print_labels = false
      end

      if attributes.key?(:'auto_print_documents')
        self.auto_print_documents = attributes[:'auto_print_documents']
      else
        self.auto_print_documents = false
      end

      if attributes.key?(:'label_printer_id')
        self.label_printer_id = attributes[:'label_printer_id']
      else
        self.label_printer_id = nil
      end

      if attributes.key?(:'document_printer_id')
        self.document_printer_id = attributes[:'document_printer_id']
      else
        self.document_printer_id = nil
      end

      if attributes.key?(:'return_shipping_rule_id')
        self.return_shipping_rule_id = attributes[:'return_shipping_rule_id']
      else
        self.return_shipping_rule_id = nil
      end

      if attributes.key?(:'auto_create_return_shipment')
        self.auto_create_return_shipment = attributes[:'auto_create_return_shipment']
      else
        self.auto_create_return_shipment = false
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'carrier')
        self.carrier = attributes[:'carrier']
      else
        self.carrier = nil
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      else
        self.address = nil
      end

      if attributes.key?(:'label_printer')
        self.label_printer = attributes[:'label_printer']
      end

      if attributes.key?(:'document_printer')
        self.document_printer = attributes[:'document_printer']
      end

      if attributes.key?(:'return_shipping_rule')
        self.return_shipping_rule = attributes[:'return_shipping_rule']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if @direction.nil?
        invalid_properties.push('invalid value for "direction", direction cannot be nil.')
      end

      if @carrier_id.nil?
        invalid_properties.push('invalid value for "carrier_id", carrier_id cannot be nil.')
      end

      if @product_id.nil?
        invalid_properties.push('invalid value for "product_id", product_id cannot be nil.')
      end

      if @services.nil?
        invalid_properties.push('invalid value for "services", services cannot be nil.')
      end

      if @additional_parameters.nil?
        invalid_properties.push('invalid value for "additional_parameters", additional_parameters cannot be nil.')
      end

      if @address_id.nil?
        invalid_properties.push('invalid value for "address_id", address_id cannot be nil.')
      end

      if @receiving_countries.nil?
        invalid_properties.push('invalid value for "receiving_countries", receiving_countries cannot be nil.')
      end

      if @email_notification.nil?
        invalid_properties.push('invalid value for "email_notification", email_notification cannot be nil.')
      end

      if @phone_notification.nil?
        invalid_properties.push('invalid value for "phone_notification", phone_notification cannot be nil.')
      end

      if @min_weight < 0
        invalid_properties.push('invalid value for "min_weight", must be greater than or equal to 0.')
      end

      if @max_weight < 0
        invalid_properties.push('invalid value for "max_weight", must be greater than or equal to 0.')
      end

      if @min_order_value < 0
        invalid_properties.push('invalid value for "min_order_value", must be greater than or equal to 0.')
      end

      if @max_order_value < 0
        invalid_properties.push('invalid value for "max_order_value", must be greater than or equal to 0.')
      end

      if @conditions.nil?
        invalid_properties.push('invalid value for "conditions", conditions cannot be nil.')
      end

      if @generate_proforma_invoice.nil?
        invalid_properties.push('invalid value for "generate_proforma_invoice", generate_proforma_invoice cannot be nil.')
      end

      if @generate_commercial_invoice.nil?
        invalid_properties.push('invalid value for "generate_commercial_invoice", generate_commercial_invoice cannot be nil.')
      end

      if @generate_packing_list.nil?
        invalid_properties.push('invalid value for "generate_packing_list", generate_packing_list cannot be nil.')
      end

      if @auto_print_labels.nil?
        invalid_properties.push('invalid value for "auto_print_labels", auto_print_labels cannot be nil.')
      end

      if @auto_print_documents.nil?
        invalid_properties.push('invalid value for "auto_print_documents", auto_print_documents cannot be nil.')
      end

      if @auto_create_return_shipment.nil?
        invalid_properties.push('invalid value for "auto_create_return_shipment", auto_create_return_shipment cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @carrier.nil?
        invalid_properties.push('invalid value for "carrier", carrier cannot be nil.')
      end

      if @address.nil?
        invalid_properties.push('invalid value for "address", address cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @name.to_s.length < 1
      return false if @direction.nil?
      direction_validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      return false unless direction_validator.valid?(@direction)
      return false if @carrier_id.nil?
      return false if @product_id.nil?
      return false if @services.nil?
      return false if @additional_parameters.nil?
      return false if @address_id.nil?
      return false if @receiving_countries.nil?
      return false if @email_notification.nil?
      return false if @phone_notification.nil?
      return false if @min_weight < 0
      return false if @max_weight < 0
      return false if @min_order_value < 0
      return false if @max_order_value < 0
      return false if @conditions.nil?
      return false if @generate_proforma_invoice.nil?
      return false if @generate_commercial_invoice.nil?
      return false if @generate_packing_list.nil?
      return false if @auto_print_labels.nil?
      return false if @auto_print_documents.nil?
      return false if @auto_create_return_shipment.nil?
      return false if @org_id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @carrier.nil?
      return false if @address.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] direction Object to be assigned
    def direction=(direction)
      validator = EnumAttributeValidator.new('String', ["outbound", "inbound"])
      unless validator.valid?(direction)
        fail ArgumentError, "invalid value for \"direction\", must be one of #{validator.allowable_values}."
      end
      @direction = direction
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_id Value to be assigned
    def carrier_id=(carrier_id)
      if carrier_id.nil?
        fail ArgumentError, 'carrier_id cannot be nil'
      end

      @carrier_id = carrier_id
    end

    # Custom attribute writer method with validation
    # @param [Object] product_id Value to be assigned
    def product_id=(product_id)
      if product_id.nil?
        fail ArgumentError, 'product_id cannot be nil'
      end

      @product_id = product_id
    end

    # Custom attribute writer method with validation
    # @param [Object] services Value to be assigned
    def services=(services)
      if services.nil?
        fail ArgumentError, 'services cannot be nil'
      end

      @services = services
    end

    # Custom attribute writer method with validation
    # @param [Object] additional_parameters Value to be assigned
    def additional_parameters=(additional_parameters)
      if additional_parameters.nil?
        fail ArgumentError, 'additional_parameters cannot be nil'
      end

      @additional_parameters = additional_parameters
    end

    # Custom attribute writer method with validation
    # @param [Object] address_id Value to be assigned
    def address_id=(address_id)
      if address_id.nil?
        fail ArgumentError, 'address_id cannot be nil'
      end

      @address_id = address_id
    end

    # Custom attribute writer method with validation
    # @param [Object] receiving_countries Value to be assigned
    def receiving_countries=(receiving_countries)
      if receiving_countries.nil?
        fail ArgumentError, 'receiving_countries cannot be nil'
      end

      @receiving_countries = receiving_countries
    end

    # Custom attribute writer method with validation
    # @param [Object] email_notification Value to be assigned
    def email_notification=(email_notification)
      if email_notification.nil?
        fail ArgumentError, 'email_notification cannot be nil'
      end

      @email_notification = email_notification
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_notification Value to be assigned
    def phone_notification=(phone_notification)
      if phone_notification.nil?
        fail ArgumentError, 'phone_notification cannot be nil'
      end

      @phone_notification = phone_notification
    end

    # Custom attribute writer method with validation
    # @param [Object] min_weight Value to be assigned
    def min_weight=(min_weight)
      if !min_weight.nil? && min_weight < 0
        fail ArgumentError, 'invalid value for "min_weight", must be greater than or equal to 0.'
      end

      @min_weight = min_weight
    end

    # Custom attribute writer method with validation
    # @param [Object] max_weight Value to be assigned
    def max_weight=(max_weight)
      if !max_weight.nil? && max_weight < 0
        fail ArgumentError, 'invalid value for "max_weight", must be greater than or equal to 0.'
      end

      @max_weight = max_weight
    end

    # Custom attribute writer method with validation
    # @param [Object] min_order_value Value to be assigned
    def min_order_value=(min_order_value)
      if !min_order_value.nil? && min_order_value < 0
        fail ArgumentError, 'invalid value for "min_order_value", must be greater than or equal to 0.'
      end

      @min_order_value = min_order_value
    end

    # Custom attribute writer method with validation
    # @param [Object] max_order_value Value to be assigned
    def max_order_value=(max_order_value)
      if !max_order_value.nil? && max_order_value < 0
        fail ArgumentError, 'invalid value for "max_order_value", must be greater than or equal to 0.'
      end

      @max_order_value = max_order_value
    end

    # Custom attribute writer method with validation
    # @param [Object] conditions Value to be assigned
    def conditions=(conditions)
      if conditions.nil?
        fail ArgumentError, 'conditions cannot be nil'
      end

      @conditions = conditions
    end

    # Custom attribute writer method with validation
    # @param [Object] generate_proforma_invoice Value to be assigned
    def generate_proforma_invoice=(generate_proforma_invoice)
      if generate_proforma_invoice.nil?
        fail ArgumentError, 'generate_proforma_invoice cannot be nil'
      end

      @generate_proforma_invoice = generate_proforma_invoice
    end

    # Custom attribute writer method with validation
    # @param [Object] generate_commercial_invoice Value to be assigned
    def generate_commercial_invoice=(generate_commercial_invoice)
      if generate_commercial_invoice.nil?
        fail ArgumentError, 'generate_commercial_invoice cannot be nil'
      end

      @generate_commercial_invoice = generate_commercial_invoice
    end

    # Custom attribute writer method with validation
    # @param [Object] generate_packing_list Value to be assigned
    def generate_packing_list=(generate_packing_list)
      if generate_packing_list.nil?
        fail ArgumentError, 'generate_packing_list cannot be nil'
      end

      @generate_packing_list = generate_packing_list
    end

    # Custom attribute writer method with validation
    # @param [Object] auto_print_labels Value to be assigned
    def auto_print_labels=(auto_print_labels)
      if auto_print_labels.nil?
        fail ArgumentError, 'auto_print_labels cannot be nil'
      end

      @auto_print_labels = auto_print_labels
    end

    # Custom attribute writer method with validation
    # @param [Object] auto_print_documents Value to be assigned
    def auto_print_documents=(auto_print_documents)
      if auto_print_documents.nil?
        fail ArgumentError, 'auto_print_documents cannot be nil'
      end

      @auto_print_documents = auto_print_documents
    end

    # Custom attribute writer method with validation
    # @param [Object] auto_create_return_shipment Value to be assigned
    def auto_create_return_shipment=(auto_create_return_shipment)
      if auto_create_return_shipment.nil?
        fail ArgumentError, 'auto_create_return_shipment cannot be nil'
      end

      @auto_create_return_shipment = auto_create_return_shipment
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier Value to be assigned
    def carrier=(carrier)
      if carrier.nil?
        fail ArgumentError, 'carrier cannot be nil'
      end

      @carrier = carrier
    end

    # Custom attribute writer method with validation
    # @param [Object] address Value to be assigned
    def address=(address)
      if address.nil?
        fail ArgumentError, 'address cannot be nil'
      end

      @address = address
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          description == o.description &&
          direction == o.direction &&
          carrier_id == o.carrier_id &&
          product_id == o.product_id &&
          services == o.services &&
          additional_parameters == o.additional_parameters &&
          address_id == o.address_id &&
          receiving_countries == o.receiving_countries &&
          email_notification == o.email_notification &&
          phone_notification == o.phone_notification &&
          min_weight == o.min_weight &&
          max_weight == o.max_weight &&
          min_order_value == o.min_order_value &&
          max_order_value == o.max_order_value &&
          conditions == o.conditions &&
          generate_proforma_invoice == o.generate_proforma_invoice &&
          generate_commercial_invoice == o.generate_commercial_invoice &&
          generate_packing_list == o.generate_packing_list &&
          auto_print_labels == o.auto_print_labels &&
          auto_print_documents == o.auto_print_documents &&
          label_printer_id == o.label_printer_id &&
          document_printer_id == o.document_printer_id &&
          return_shipping_rule_id == o.return_shipping_rule_id &&
          auto_create_return_shipment == o.auto_create_return_shipment &&
          org_id == o.org_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          carrier == o.carrier &&
          address == o.address &&
          label_printer == o.label_printer &&
          document_printer == o.document_printer &&
          return_shipping_rule == o.return_shipping_rule
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, description, direction, carrier_id, product_id, services, additional_parameters, address_id, receiving_countries, email_notification, phone_notification, min_weight, max_weight, min_order_value, max_order_value, conditions, generate_proforma_invoice, generate_commercial_invoice, generate_packing_list, auto_print_labels, auto_print_documents, label_printer_id, document_printer_id, return_shipping_rule_id, auto_create_return_shipment, org_id, created_at, updated_at, carrier, address, label_printer, document_printer, return_shipping_rule].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
