=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class ListOrgWebhookDeliveries200ResponseDataInner < ApiModelBase
    # Delivery log ID
    attr_accessor :id

    # ID of the webhook this delivery belongs to
    attr_accessor :webhook_id

    # Event type that was delivered
    attr_accessor :event

    # JSON payload that was sent
    attr_accessor :payload

    # HTTP status code returned by the endpoint
    attr_accessor :status_code

    # Response body returned by the endpoint
    attr_accessor :response

    # Request duration in milliseconds
    attr_accessor :duration

    # Whether the delivery succeeded
    attr_accessor :success

    # Delivery attempt number
    attr_accessor :attempt

    # Error message if the delivery failed
    attr_accessor :error

    # Delivery timestamp (ISO 8601)
    attr_accessor :created_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'webhook_id' => :'webhookId',
        :'event' => :'event',
        :'payload' => :'payload',
        :'status_code' => :'statusCode',
        :'response' => :'response',
        :'duration' => :'duration',
        :'success' => :'success',
        :'attempt' => :'attempt',
        :'error' => :'error',
        :'created_at' => :'createdAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'webhook_id' => :'String',
        :'event' => :'String',
        :'payload' => :'Object',
        :'status_code' => :'Float',
        :'response' => :'String',
        :'duration' => :'Float',
        :'success' => :'Boolean',
        :'attempt' => :'Float',
        :'error' => :'String',
        :'created_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'payload',
        :'status_code',
        :'response',
        :'duration',
        :'error',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::ListOrgWebhookDeliveries200ResponseDataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::ListOrgWebhookDeliveries200ResponseDataInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'webhook_id')
        self.webhook_id = attributes[:'webhook_id']
      else
        self.webhook_id = nil
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      else
        self.event = nil
      end

      if attributes.key?(:'payload')
        self.payload = attributes[:'payload']
      else
        self.payload = nil
      end

      if attributes.key?(:'status_code')
        self.status_code = attributes[:'status_code']
      else
        self.status_code = nil
      end

      if attributes.key?(:'response')
        self.response = attributes[:'response']
      else
        self.response = nil
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      else
        self.duration = nil
      end

      if attributes.key?(:'success')
        self.success = attributes[:'success']
      else
        self.success = nil
      end

      if attributes.key?(:'attempt')
        self.attempt = attributes[:'attempt']
      else
        self.attempt = nil
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      else
        self.error = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @webhook_id.nil?
        invalid_properties.push('invalid value for "webhook_id", webhook_id cannot be nil.')
      end

      if @event.nil?
        invalid_properties.push('invalid value for "event", event cannot be nil.')
      end

      if @success.nil?
        invalid_properties.push('invalid value for "success", success cannot be nil.')
      end

      if @attempt.nil?
        invalid_properties.push('invalid value for "attempt", attempt cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @webhook_id.nil?
      return false if @event.nil?
      return false if @success.nil?
      return false if @attempt.nil?
      return false if @created_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] webhook_id Value to be assigned
    def webhook_id=(webhook_id)
      if webhook_id.nil?
        fail ArgumentError, 'webhook_id cannot be nil'
      end

      @webhook_id = webhook_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event Value to be assigned
    def event=(event)
      if event.nil?
        fail ArgumentError, 'event cannot be nil'
      end

      @event = event
    end

    # Custom attribute writer method with validation
    # @param [Object] success Value to be assigned
    def success=(success)
      if success.nil?
        fail ArgumentError, 'success cannot be nil'
      end

      @success = success
    end

    # Custom attribute writer method with validation
    # @param [Object] attempt Value to be assigned
    def attempt=(attempt)
      if attempt.nil?
        fail ArgumentError, 'attempt cannot be nil'
      end

      @attempt = attempt
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          webhook_id == o.webhook_id &&
          event == o.event &&
          payload == o.payload &&
          status_code == o.status_code &&
          response == o.response &&
          duration == o.duration &&
          success == o.success &&
          attempt == o.attempt &&
          error == o.error &&
          created_at == o.created_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, webhook_id, event, payload, status_code, response, duration, success, attempt, error, created_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
