=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class ListCarriers200ResponseDataInner < ApiModelBase
    # Unique carrier identifier
    attr_accessor :id

    # Carrier display name
    attr_accessor :name

    # Carrier slug identifier
    attr_accessor :carrier_slug

    # Carrier configuration (required and optional fields)
    attr_accessor :config

    # Owning organization ID
    attr_accessor :org_id

    # Creation timestamp (ISO 8601)
    attr_accessor :created_at

    # Last update timestamp (ISO 8601)
    attr_accessor :updated_at

    # Carrier logo URL
    attr_accessor :logo

    # Carrier brand color (hex)
    attr_accessor :brand_color

    # Whether this carrier integration is deprecated (still works, but discouraged)
    attr_accessor :deprecated

    # Guidance shown alongside the deprecated tag (e.g. what to migrate to)
    attr_accessor :deprecation_message

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'carrier_slug' => :'carrierSlug',
        :'config' => :'config',
        :'org_id' => :'orgId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'logo' => :'logo',
        :'brand_color' => :'brandColor',
        :'deprecated' => :'deprecated',
        :'deprecation_message' => :'deprecationMessage'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'carrier_slug' => :'String',
        :'config' => :'Hash<String, ListCarriers200ResponseDataInnerConfigValue>',
        :'org_id' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'logo' => :'String',
        :'brand_color' => :'String',
        :'deprecated' => :'Boolean',
        :'deprecation_message' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::ListCarriers200ResponseDataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::ListCarriers200ResponseDataInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'carrier_slug')
        self.carrier_slug = attributes[:'carrier_slug']
      else
        self.carrier_slug = nil
      end

      if attributes.key?(:'config')
        if (value = attributes[:'config']).is_a?(Hash)
          self.config = value
        end
      else
        self.config = nil
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'logo')
        self.logo = attributes[:'logo']
      end

      if attributes.key?(:'brand_color')
        self.brand_color = attributes[:'brand_color']
      end

      if attributes.key?(:'deprecated')
        self.deprecated = attributes[:'deprecated']
      end

      if attributes.key?(:'deprecation_message')
        self.deprecation_message = attributes[:'deprecation_message']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @carrier_slug.nil?
        invalid_properties.push('invalid value for "carrier_slug", carrier_slug cannot be nil.')
      end

      if @config.nil?
        invalid_properties.push('invalid value for "config", config cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @carrier_slug.nil?
      return false if @config.nil?
      return false if @org_id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] carrier_slug Value to be assigned
    def carrier_slug=(carrier_slug)
      if carrier_slug.nil?
        fail ArgumentError, 'carrier_slug cannot be nil'
      end

      @carrier_slug = carrier_slug
    end

    # Custom attribute writer method with validation
    # @param [Object] config Value to be assigned
    def config=(config)
      if config.nil?
        fail ArgumentError, 'config cannot be nil'
      end

      @config = config
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          carrier_slug == o.carrier_slug &&
          config == o.config &&
          org_id == o.org_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          logo == o.logo &&
          brand_color == o.brand_color &&
          deprecated == o.deprecated &&
          deprecation_message == o.deprecation_message
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, carrier_slug, config, org_id, created_at, updated_at, logo, brand_color, deprecated, deprecation_message].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
