=begin
#Zippendo Public API

#Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).

The version of the OpenAPI document: 1.0.0
Contact: support@zippendo.com
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module Zippendo
  class TrackShipment200Response < ApiModelBase
    # Carrier tracking number.
    attr_accessor :tracking_number

    # Public carrier tracking URL.
    attr_accessor :tracking_url

    # Latest normalized tracking status.
    attr_accessor :current_status

    # Estimated delivery timestamp.
    attr_accessor :estimated_delivery

    # Tracking events ordered from newest to oldest.
    attr_accessor :events

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tracking_number' => :'trackingNumber',
        :'tracking_url' => :'trackingUrl',
        :'current_status' => :'currentStatus',
        :'estimated_delivery' => :'estimatedDelivery',
        :'events' => :'events'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tracking_number' => :'String',
        :'tracking_url' => :'String',
        :'current_status' => :'String',
        :'estimated_delivery' => :'String',
        :'events' => :'Array<TrackShipment200ResponseEventsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tracking_number',
        :'tracking_url',
        :'current_status',
        :'estimated_delivery',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zippendo::TrackShipment200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zippendo::TrackShipment200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      else
        self.tracking_number = nil
      end

      if attributes.key?(:'tracking_url')
        self.tracking_url = attributes[:'tracking_url']
      else
        self.tracking_url = nil
      end

      if attributes.key?(:'current_status')
        self.current_status = attributes[:'current_status']
      else
        self.current_status = nil
      end

      if attributes.key?(:'estimated_delivery')
        self.estimated_delivery = attributes[:'estimated_delivery']
      end

      if attributes.key?(:'events')
        if (value = attributes[:'events']).is_a?(Array)
          self.events = value
        end
      else
        self.events = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @events.nil?
        invalid_properties.push('invalid value for "events", events cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      current_status_validator = EnumAttributeValidator.new('String', ["created", "awaiting_pickup", "picked_up", "in_transit", "out_for_delivery", "ready_for_pickup", "delivered", "returned", "exception"])
      return false unless current_status_validator.valid?(@current_status)
      return false if @events.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] current_status Object to be assigned
    def current_status=(current_status)
      validator = EnumAttributeValidator.new('String', ["created", "awaiting_pickup", "picked_up", "in_transit", "out_for_delivery", "ready_for_pickup", "delivered", "returned", "exception"])
      unless validator.valid?(current_status)
        fail ArgumentError, "invalid value for \"current_status\", must be one of #{validator.allowable_values}."
      end
      @current_status = current_status
    end

    # Custom attribute writer method with validation
    # @param [Object] events Value to be assigned
    def events=(events)
      if events.nil?
        fail ArgumentError, 'events cannot be nil'
      end

      @events = events
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tracking_number == o.tracking_number &&
          tracking_url == o.tracking_url &&
          current_status == o.current_status &&
          estimated_delivery == o.estimated_delivery &&
          events == o.events
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tracking_number, tracking_url, current_status, estimated_delivery, events].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
